-- Add hearts economy fields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyHeartsUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastHeartsResetDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bonusHearts" INTEGER NOT NULL DEFAULT 0;

-- Add one-time purchase fields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasPdfAccess" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasChapterUnlock" BOOLEAN NOT NULL DEFAULT false;
